### ISSUE TITLE
Any language request end up with "KO - KEY NOT FOUND" exception

### ISSUE THREAD

**Issue by AndreyVyalov** [markozajc/Akiwrapper#7]
Probably akinator API has changed

**Comment by markozajc** [comment]
Temporarily fixed in 1.3.4.1 . Research is being made into the volatile querystring parameters `uid_ext_session` and `frontaddr`.

**Comment by rontoking** [comment]
It still throws KO - KEY NOT FOUND for me even with 1,3,4,1 when it reaches `new AkiwrapperBuilder().build();`

**Comment by markozajc** [comment]
The issue has appeared again, shortly after the patch. Seems like acquiring the right querystring parameters will be required.

**Comment by markozajc** [comment]
The problematic parameter seems to be `uid_ext_session`. Any help with finding out where and how the website version of Akinator generates it is highly appreciated.
